name: moneys

services:
  php:
    container_name: php
    build:
      context: ./docker/
      dockerfile: dphp
    volumes:
      - ~/dev/scratches:/var/www/scratches
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    depends_on:
      - db

  cli:
    container_name: cli
    build:
      context: ./docker/
      dockerfile: dcli
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    tty: true

  db:
    container_name: ${DB_HOST}
    image: mariadb:11.6-ubi
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    ports:
      - "3306:3306"

  nginx:
    container_name: nginx
    volumes:
      - .:/var/www/html
    build:
      context: ./docker/
      dockerfile: dnginx
    depends_on:
      - php
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

  node:
    container_name: watch
    image: node:latest
    volumes:
      - .:var/www/html
    command:
      - npm init

  node-watch:
    container_name: node-watch
    image: node:latest
    volumes:
      - .:/var/www/html
    depends_on:
      node:
        condition: service_started
    command:
      - npm run watch



volumes:
  dbdata: